// frontend/components/ui/export-button.jsx
import { useState } from "react";

export function ExportButton({ baseUrl = "" }) {
  const [open, setOpen] = useState(false);

  function handleExport(format) {
    const sep = baseUrl.includes("?") ? "&" : "?";
    window.open(`${baseUrl}${sep}format=${format}`, "_blank");
    setOpen(false);
  }

  return (
    <div className="relative inline-flex" onBlur={(e) => { if (!e.currentTarget.contains(e.relatedTarget)) setOpen(false); }}>
      <button
        className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold rounded-lg border border-[var(--color-border)] bg-[var(--color-bg)] text-[var(--color-fg-tertiary)] cursor-pointer hover:bg-[var(--color-surface)] transition-colors font-[inherit]"
        onClick={() => setOpen((o) => !o)}
      >
        Export
        <svg width="10" height="10" viewBox="0 0 10 10" fill="none">
          <path d="M2.5 4 5 6.5 7.5 4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
      </button>
      {open && (
        <div className="absolute right-0 top-full mt-1 bg-[var(--color-bg)] border border-[var(--color-border)] rounded-lg shadow-[var(--shadow-md)] z-10 min-w-[6rem] overflow-hidden">
          {["csv", "json"].map((fmt) => (
            <button
              key={fmt}
              className="block w-full px-4 py-2 text-xs font-medium text-left text-[var(--color-fg-tertiary)] cursor-pointer bg-transparent border-none hover:bg-[var(--color-surface)] transition-colors font-[inherit]"
              onClick={() => handleExport(fmt)}
            >
              {fmt.toUpperCase()}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

// frontend/components/ui/ExportButton.svelte
<script>
  /**
   * Dropdown button for CSV/JSON export
   * @type {{ baseUrl?: string }}
   */
  let { baseUrl = "" } = $props();

  let open = $state(false);

  function handleExport(format) {
    const separator = baseUrl.includes('?') ? '&' : '?';
    window.open(`${baseUrl}${separator}format=${format}`, '_blank');
    open = false;
  }

  function handleClickOutside(event) {
    if (!event.currentTarget.contains(event.relatedTarget)) {
      open = false;
    }
  }
</script>

<div class="export-wrapper" onfocusout={handleClickOutside}>
  <button class="export-btn" onclick={() => (open = !open)}>
    Export
    <svg width="10" height="10" viewBox="0 0 10 10" fill="none" aria-hidden="true">
      <path d="M2.5 4 5 6.5 7.5 4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
    </svg>
  </button>
  {#if open}
    <div class="export-dropdown">
      <button class="export-option" onclick={() => handleExport('csv')}>CSV</button>
      <button class="export-option" onclick={() => handleExport('json')}>JSON</button>
    </div>
  {/if}
</div>

<style>
  .export-wrapper {
    position: relative;
    display: inline-flex;
    margin-left: auto;
  }

  .export-btn {
    display: inline-flex;
    align-items: center;
    gap: 0.375rem;
    padding: 0.375rem 0.75rem;
    font-size: 0.8125rem;
    font-weight: 500;
    font-family: inherit;
    background: var(--color-bg);
    color: var(--color-fg);
    border: 1px solid var(--color-border);
    border-radius: var(--radius-sm);
    box-shadow: 0 1px 2px 0 rgb(0 0 0 / 0.05);
    cursor: pointer;
    transition: all 0.15s ease;

    &:hover {
      background: var(--color-accent);
      border-color: var(--color-input-border);
    }

    &:active {
      transform: translateY(0.5px);
    }
  }

  .export-dropdown {
    position: absolute;
    top: calc(100% + 0.25rem);
    right: 0;
    background: var(--color-bg);
    border: 1px solid var(--color-border);
    border-radius: var(--radius-sm);
    box-shadow: 0 4px 12px rgb(0 0 0 / 0.1);
    z-index: 20;
    min-width: 5rem;
    overflow: hidden;
  }

  .export-option {
    display: block;
    width: 100%;
    padding: 0.4375rem 0.75rem;
    font-size: 0.8125rem;
    font-weight: 500;
    font-family: inherit;
    background: transparent;
    color: var(--color-fg);
    border: none;
    cursor: pointer;
    text-align: left;
    transition: background 0.1s ease;

    &:hover {
      background: var(--color-accent);
    }

    &:not(:last-child) {
      border-bottom: 1px solid var(--color-border);
    }
  }
</style>
