// frontend/components/ui/stat-card.jsx
import { cn } from "@/lib/utils.js";

export function StatCard({ label, value, color, danger }) {
  return (
    <div
      className={cn(
        "bg-[var(--color-bg)] border border-[var(--color-border)] rounded-xl p-5 flex flex-col gap-1 transition-shadow hover:shadow-[var(--shadow-md)]",
        danger && "border-[var(--color-danger-border)]",
      )}
    >
      <span className="text-[0.8125rem] font-medium text-[var(--color-muted)]">{label}</span>
      <span
        className={cn(
          "text-[1.75rem] font-bold leading-none tabular-nums tracking-tight",
          danger ? "text-[var(--color-danger)]" : "text-[var(--color-fg)]",
        )}
        style={color && !danger ? { color } : undefined}
      >
        {value}
      </span>
    </div>
  );
}

// frontend/components/ui/StatCard.svelte
<script>
let { label, value, color = "", danger = false } = $props();
</script>

<div class="stat-card" class:stat-card-danger={danger}>
  <span class="stat-card-label">{label}</span>
  <span class="stat-card-value" class:stat-value-danger={danger} style={color ? `color: ${color}` : ""}>
    {value}
  </span>
</div>

<style>
  .stat-card {
    background: var(--color-bg);
    border: 1px solid var(--color-border);
    border-radius: var(--radius-lg);
    padding: 1.25rem;
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
    transition: border-color 0.15s, box-shadow 0.15s;

    &:hover {
      box-shadow: var(--shadow-md);
    }
  }

  .stat-card-danger {
    border-color: var(--color-danger-border);
  }

  .stat-card-label {
    font-size: 0.8125rem;
    font-weight: 500;
    color: var(--color-muted);
  }

  .stat-card-value {
    font-size: 1.75rem;
    font-weight: 700;
    color: var(--color-fg);
    letter-spacing: -0.02em;
    line-height: 1;
    font-variant-numeric: tabular-nums;
  }

  .stat-value-danger {
    color: var(--color-danger);
  }
</style>
