// frontend/pages/cache/index.jsx
import { useState } from "react";
import { router, InfiniteScroll } from "@inertiajs/react";
import DaylightLayout from "../DaylightLayout";
import PeriodSelect from "../PeriodSelect";
import EwSheet from "../errors/EwSheet";
import AreaChart from "@/components/charts/AreaChart";
import DonutChart from "@/components/charts/DonutChart";
import { SortableHeader } from "@/components/ui/sortable-header";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { fmt } from "@/lib/formatters.js";

function patternHitRateClass(rate) {
  if (rate == null) return "";
  if (rate >= 90) return "rate-ok";
  if (rate >= 70) return "rate-warn";
  return "rate-danger";
}

export default function CacheIndex({
  key_groups = [], period = "24h", total_events = 0,
  hit_rate = 0, total_reads = 0, total_hits = 0,
  volume_series = [], base_path: base = "/daylight",
  sort_column = null, sort_direction = null,
}) {
  const [sheetOpen, setSheetOpen] = useState(false);
  const [sheetItem, setSheetItem] = useState(null);

  const hitRateDisplay = `${hit_rate.toFixed(1)}%`;
  const hitRateClass = hit_rate >= 90 ? "dl-stat-ok" : hit_rate >= 70 ? "dl-stat-warn" : "dl-stat-danger";
  const misses = total_reads - total_hits;

  const donutSegments = [
    { value: total_hits, color: "#22c55e", label: "Hits" },
    { value: misses, color: "#ef4444", label: "Misses" },
  ].filter((s) => s.value > 0);

  const sheetAi = sheetItem
    ? `Cache Key Pattern: ${sheetItem.key_pattern}\nReads: ${sheetItem.reads}\nHit Rate: ${sheetItem.hit_rate != null ? sheetItem.hit_rate.toFixed(1) + "%" : "N/A"}\nAvg Duration: ${fmt(sheetItem.avg_duration)}`
    : "";

  function changePeriod(p) { router.get(`${base}/cache`, { period: p }, { preserveState: true }); }
  function openPattern(p) { setSheetItem(p); setSheetOpen(true); }

  return (
    <DaylightLayout>
      <div className="dl-page">
        <div className="dl-page-header">
          <div>
            <h1 className="dl-page-title">Cache</h1>
            <p className="dl-page-subtitle">Cache performance and key patterns in the last {period}</p>
          </div>
          <div className="dl-period-selector">
            <PeriodSelect value={period} onChange={changePeriod} />
          </div>
        </div>

        <div className="dl-stat-grid">
          <div className="dl-stat-card">
            <span className="stat-card-label">Hit Rate</span>
            <span className={`stat-card-value ${hitRateClass}`}>{hitRateDisplay}</span>
          </div>
          <div className="dl-stat-card">
            <span className="stat-card-label">Total Reads</span>
            <span className="stat-card-value">{total_reads.toLocaleString()}</span>
          </div>
          <div className="dl-stat-card">
            <span className="stat-card-label">Cache Hits</span>
            <span className="stat-card-value">{total_hits.toLocaleString()}</span>
          </div>
          <div className="dl-stat-card">
            <span className="stat-card-label">Total Events</span>
            <span className="stat-card-value">{total_events.toLocaleString()}</span>
          </div>
        </div>

        <div className="dl-charts-row">
          {(total_hits + misses) > 0 && (
            <Card className="chart-card-donut">
              <CardHeader className="border-b">
                <CardTitle className="text-sm">Hits vs Misses</CardTitle>
              </CardHeader>
              <CardContent className="card-body-center">
                <DonutChart segments={donutSegments} size={110} strokeWidth={12} centerValue={hitRateDisplay} centerLabel="hit rate" />
              </CardContent>
            </Card>
          )}
          {volume_series.length >= 2 && (
            <Card className="chart-card-volume">
              <CardHeader className="border-b">
                <CardTitle className="text-sm">Cache Event Volume</CardTitle>
                <span className="dl-card-subtitle">Over time</span>
              </CardHeader>
              <CardContent>
                <AreaChart data={volume_series} width={420} height={80} color="#8b5cf6" />
              </CardContent>
            </Card>
          )}
        </div>

        <Card>
          <CardHeader className="border-b">
            <CardTitle className="text-sm">Key Patterns</CardTitle>
            <span className="dl-card-subtitle">{key_groups.length} patterns</span>
          </CardHeader>
          <div className="dl-data-table">
            {key_groups.length === 0 ? (
              <div className="dl-table-empty">
                <svg width="24" height="24" fill="none" stroke="#94a3b8" strokeWidth="1.5" viewBox="0 0 24 24"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg>
                <span>No cache events recorded in this period.</span>
              </div>
            ) : (
              <InfiniteScroll data="key_groups" itemsElement="#cache-tbody" startElement="#cache-thead">
                <table className="dl-table">
                  <thead id="cache-thead">
                    <tr>
                      <th style={{ flex: 3 }}>Key Pattern</th>
                      <th style={{ width: "5rem", textAlign: "right" }}><SortableHeader column="reads" label="Reads" sort_column={sort_column} sort_direction={sort_direction} /></th>
                      <th style={{ width: "5.5rem", textAlign: "right" }}>Hit Rate</th>
                      <th style={{ width: "5rem", textAlign: "right" }}><SortableHeader column="avg_duration" label="Avg" sort_column={sort_column} sort_direction={sort_direction} /></th>
                    </tr>
                  </thead>
                  <tbody id="cache-tbody">
                    {key_groups.map((p, i) => (
                      <tr key={`${p.key_pattern}:${i}`} className="row" onClick={() => openPattern(p)} style={{ cursor: "pointer" }}>
                        <td className="cell td-key" style={{ flex: 3 }}>
                          <span className="key-text">{p.key_pattern}</span>
                        </td>
                        <td className="cell num" style={{ width: "5rem" }}>{p.reads}</td>
                        <td className="cell num" style={{ width: "5.5rem" }}>
                          <span className={patternHitRateClass(p.hit_rate)}>
                            {p.hit_rate != null ? `${p.hit_rate.toFixed(1)}%` : "—"}
                          </span>
                        </td>
                        <td className="cell num" style={{ width: "5rem" }}>{fmt(p.avg_duration)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </InfiniteScroll>
            )}
          </div>
        </Card>
      </div>

      <EwSheet open={sheetOpen} onClose={() => setSheetOpen(false)} title="Cache Pattern Detail" aiContext={sheetAi}>
        {sheetItem && (
          <div className="dl-sheet-detail">
            <dl className="dl-dl">
              <div className="dl-dl-row"><dt>Key Pattern</dt><dd className="dl-mono">{sheetItem.key_pattern}</dd></div>
              <div className="dl-dl-row"><dt>Reads</dt><dd>{sheetItem.reads}</dd></div>
              <div className="dl-dl-row">
                <dt>Hit Rate</dt>
                <dd className={patternHitRateClass(sheetItem.hit_rate)}>
                  {sheetItem.hit_rate != null ? `${sheetItem.hit_rate.toFixed(1)}%` : "—"}
                </dd>
              </div>
              <div className="dl-dl-row"><dt>Avg Duration</dt><dd>{fmt(sheetItem.avg_duration)}</dd></div>
              {sheetItem.max_duration && <div className="dl-dl-row"><dt>Max Duration</dt><dd>{fmt(sheetItem.max_duration)}</dd></div>}
              {sheetItem.total && <div className="dl-dl-row"><dt>Total Events</dt><dd>{sheetItem.total}</dd></div>}
            </dl>
          </div>
        )}
      </EwSheet>
    </DaylightLayout>
  );
}

// frontend/pages/cache/index.svelte
<script>
  import { router } from "@inertiajs/svelte";
  import { fmt } from "@/lib/formatters.js";
  import DaylightLayout from "../DaylightLayout.svelte";
  import PeriodSelect from "../PeriodSelect.svelte";
  import EwSheet from "../errors/EwSheet.svelte";
  import SortableHeader from "@/components/ui/SortableHeader.svelte";
  import AreaChart from "@/components/charts/AreaChart.svelte";
  import DonutChart from "@/components/charts/DonutChart.svelte";
  import InfiniteScroll from "@/components/ui/InfiniteScroll.svelte";

  let { stats = {}, patterns = [], period = "24h", total_events = 0, volume_series = [], page = 1, has_more = false, base_path: base = "/daylight", sort_column = null, sort_direction = null } = $props();

  let sheetOpen = $state(false);
  let sheetItem = $state(null);

  function changePeriod(p) { router.get(`${base}/cache`, { period: p }, { preserveState: true }); }

  let hitRate = $derived(stats.hit_rate != null ? stats.hit_rate : 0);
  let hitRateDisplay = $derived(`${(hitRate * 100).toFixed(1)}%`);
  let hitRateClass = $derived(hitRate >= 0.9 ? "dl-stat-ok" : hitRate >= 0.7 ? "dl-stat-warn" : "dl-stat-danger");

  let totalReads = $derived(stats.total_reads || 0);
  let totalWrites = $derived(stats.total_writes || 0);
  let totalDeletes = $derived(stats.total_deletes || 0);

  let hits = $derived(stats.hits || 0);
  let misses = $derived(stats.misses || 0);

  let donutSegments = $derived([
    { value: hits, color: "#22c55e", label: "Hits" },
    { value: misses, color: "#ef4444", label: "Misses" },
  ].filter(s => s.value > 0));

  function openPattern(p) { sheetItem = p; sheetOpen = true; }

  let sheetAi = $derived.by(() => {
    if (!sheetItem) return "";
    return `Cache Key Pattern: ${sheetItem.key_pattern}\nReads: ${sheetItem.reads}\nWrites: ${sheetItem.writes}\nHit Rate: ${sheetItem.hit_rate != null ? (sheetItem.hit_rate * 100).toFixed(1) + "%" : "N/A"}\nAvg Duration: ${fmt(sheetItem.avg_duration)}`;
  });

  let allPatterns = $state(patterns);
  let currentPage = $state(page);
  let loadingMore = $state(false);

  $effect(() => {
    period;
    allPatterns = patterns;
    currentPage = page;
  });

  function loadMore() {
    if (loadingMore || !has_more) return;
    loadingMore = true;
    router.get(`${base}/cache`, { period, page: currentPage + 1 }, {
      preserveState: true,
      preserveScroll: true,
      only: ['patterns', 'page', 'has_more'],
      onSuccess: (p) => {
        const newItems = p.props.patterns || [];
        allPatterns = [...allPatterns, ...newItems];
        currentPage = p.props.page;
        has_more = p.props.has_more;
        loadingMore = false;
      },
      onError: () => { loadingMore = false; }
    });
  }

  function patternHitRateClass(rate) {
    if (rate == null) return "";
    if (rate >= 0.9) return "rate-ok";
    if (rate >= 0.7) return "rate-warn";
    return "rate-danger";
  }
</script>

<svelte:head><title>Cache — Daylight</title></svelte:head>

<DaylightLayout>
  <div class="dl-page">
    <!-- Header -->
    <div class="dl-page-header">
      <div>
        <h1 class="dl-page-title">Cache</h1>
        <p class="dl-page-subtitle">Cache performance and key patterns in the last {period}</p>
      </div>
      <div class="dl-period-selector">
        <PeriodSelect value={period} onchange={changePeriod} />
      </div>
    </div>

    <!-- Stat Cards -->
    <div class="dl-stat-grid">
      <div class="dl-stat-card">
        <span class="stat-card-label">Hit Rate</span>
        <span class="stat-card-value {hitRateClass}">{hitRateDisplay}</span>
      </div>
      <div class="dl-stat-card">
        <span class="stat-card-label">Total Reads</span>
        <span class="stat-card-value">{totalReads.toLocaleString()}</span>
      </div>
      <div class="dl-stat-card">
        <span class="stat-card-label">Total Writes</span>
        <span class="stat-card-value">{totalWrites.toLocaleString()}</span>
      </div>
      <div class="dl-stat-card">
        <span class="stat-card-label">Total Deletes</span>
        <span class="stat-card-value">{totalDeletes.toLocaleString()}</span>
      </div>
    </div>

    <!-- Donut + Volume Charts -->
    <div class="dl-charts-row">
      {#if (hits + misses) > 0}
        <div class="dl-card chart-card-donut">
          <div class="dl-card-header">
            <h2 class="dl-card-title">Hits vs Misses</h2>
          </div>
          <div class="dl-card-body card-body-center">
            <DonutChart
              segments={donutSegments}
              size={110}
              strokeWidth={12}
              centerValue={hitRateDisplay}
              centerLabel="hit rate"
            />
          </div>
        </div>
      {/if}
      {#if volume_series.length >= 2}
        <div class="dl-card chart-card-volume">
          <div class="dl-card-header">
            <h2 class="dl-card-title">Cache Event Volume</h2>
            <span class="dl-card-subtitle">Over time</span>
          </div>
          <div class="dl-card-body">
            <AreaChart data={volume_series} width={420} height={80} color="#8b5cf6" />
          </div>
        </div>
      {/if}
    </div>

    <!-- Cache Patterns Table -->
    <div class="dl-card">
      <div class="dl-card-header">
        <h2 class="dl-card-title">Key Patterns</h2>
        <span class="dl-card-subtitle">{patterns.length} patterns</span>
      </div>
      <div class="dl-data-table">
        <div class="dl-table-header">
          <div class="dl-th" style="flex:3">Key Pattern</div>
          <div class="dl-th dl-th-right" style="width:5rem"><SortableHeader column="reads" label="Reads" {sort_column} {sort_direction} /></div>
          <div class="dl-th dl-th-right" style="width:5rem"><SortableHeader column="writes" label="Writes" {sort_column} {sort_direction} /></div>
          <div class="dl-th dl-th-right" style="width:5.5rem">Hit Rate</div>
          <div class="dl-th dl-th-right" style="width:5rem"><SortableHeader column="avg_duration" label="Avg" {sort_column} {sort_direction} /></div>
        </div>
        {#each allPatterns as p, i (p.key_pattern + ':' + i)}
          <button class="dl-table-row" onclick={() => openPattern(p)}>
            <div class="dl-td td-key" style="flex:3">
              <span class="key-text">{p.key_pattern}</span>
            </div>
            <div class="dl-td dl-td-num" style="width:5rem">{p.reads}</div>
            <div class="dl-td dl-td-num" style="width:5rem">{p.writes}</div>
            <div class="dl-td dl-td-num" style="width:5.5rem">
              <span class={patternHitRateClass(p.hit_rate)}>{p.hit_rate != null ? `${(p.hit_rate * 100).toFixed(1)}%` : "\u2014"}</span>
            </div>
            <div class="dl-td dl-td-num" style="width:5rem">{fmt(p.avg_duration)}</div>
          </button>
        {/each}
        {#if allPatterns.length === 0}
          <div class="dl-table-empty">
            <svg width="24" height="24" fill="none" stroke="#94a3b8" stroke-width="1.5" viewBox="0 0 24 24"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg>
            <span>No cache events recorded in this period.</span>
          </div>
        {/if}
        <InfiniteScroll loading={loadingMore} hasMore={has_more} onLoadMore={loadMore} />
      </div>
    </div>
  </div>
</DaylightLayout>

<EwSheet bind:open={sheetOpen} title="Cache Pattern Detail" aiContext={sheetAi}>
  {#if sheetItem}
    <div class="dl-sheet-detail">
      <dl class="dl-dl">
        <div class="dl-dl-row"><dt>Key Pattern</dt><dd class="dl-mono">{sheetItem.key_pattern}</dd></div>
        <div class="dl-dl-row"><dt>Reads</dt><dd>{sheetItem.reads}</dd></div>
        <div class="dl-dl-row"><dt>Writes</dt><dd>{sheetItem.writes}</dd></div>
        <div class="dl-dl-row"><dt>Hit Rate</dt><dd class={patternHitRateClass(sheetItem.hit_rate)}>{sheetItem.hit_rate != null ? `${(sheetItem.hit_rate * 100).toFixed(1)}%` : "\u2014"}</dd></div>
        <div class="dl-dl-row"><dt>Avg Duration</dt><dd>{fmt(sheetItem.avg_duration)}</dd></div>
        {#if sheetItem.max_duration}<div class="dl-dl-row"><dt>Max Duration</dt><dd>{fmt(sheetItem.max_duration)}</dd></div>{/if}
        {#if sheetItem.total}<div class="dl-dl-row"><dt>Total Events</dt><dd>{sheetItem.total}</dd></div>{/if}
      </dl>
    </div>
  {/if}
</EwSheet>

<style>
  /* Stat Card (page-specific, not yet in global CSS) */
  .dl-stat-card {
    background: var(--color-bg);
    border: 1px solid var(--color-border);
    border-radius: 0.75rem;
    padding: 1.25rem;
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
  }

  .stat-card-label {
    font-size: 0.8125rem;
    font-weight: 500;
    color: var(--color-muted);
  }

  .stat-card-value {
    font-size: 1.75rem;
    font-weight: 700;
    color: var(--color-fg);
    letter-spacing: -0.02em;
    line-height: 1;
    font-variant-numeric: tabular-nums;
  }

  /* Chart cards (page-specific sizing) */
  .chart-card-donut {
    min-width: 280px;
  }

  .chart-card-volume {
    min-width: 0;
  }

  .card-body-center {
    display: flex;
    align-items: center;
    justify-content: center;
  }

  /* Table key column */
  .td-key {
    min-width: 0;
  }

  .key-text {
    font-family: "SF Mono", Monaco, Menlo, Consolas, monospace;
    font-size: 0.75rem;
    color: var(--color-fg-tertiary);
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    display: block;
  }

  /* Hit-rate coloring in table rows */
  .rate-ok { color: var(--color-success); font-weight: 600; }
  .rate-warn { color: var(--color-warning); font-weight: 600; }
  .rate-danger { color: var(--color-danger); font-weight: 600; }
</style>
