// frontend/components/errors/EwAiChat.jsx
import { useState, useRef, useEffect } from "react";
import { usePage } from "@inertiajs/react";
import { consumer } from "@/utils/cable";
import AiChatMessages from "@/components/ai-chat/AiChatMessages";
import AiChatInput from "@/components/ai-chat/AiChatInput";
import { Button } from "@/components/ui/button";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { playNotificationSound } from "@/lib/notification-sounds.js";

export default function EwAiChat({ context = "", appContext = "" }) {
  const { props } = usePage();
  const aiModels = props.aiModels || [];
  const defaultAiModel = props.defaultAiModel || "";

  const [selectedModel, setSelectedModel] = useState(() => defaultAiModel || aiModels[0]?.value || "");
  const [chatId, setChatId] = useState(null);
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState("");
  const [references, setReferences] = useState([]);
  const [sending, setSending] = useState(false);
  const [streaming, setStreaming] = useState("");
  const [toolStatus, setToolStatus] = useState("");
  const [toolLog, setToolLog] = useState([]);
  const [toolCalls, setToolCalls] = useState([]);
  const [thinkingStream, setThinkingStream] = useState("");
  const [thinkingDone, setThinkingDone] = useState(false);
  const [thinkingDuration, setThinkingDuration] = useState(0);
  const [executingActions, setExecutingActions] = useState({});
  const [executedActions, setExecutedActions] = useState({});
  const [chatScope, setChatScope] = useState("standard");

  const chatIdRef = useRef(null);
  const subscriptionRef = useRef(null);
  const inputElRef = useRef(null);

  useEffect(() => { chatIdRef.current = chatId; }, [chatId]);

  useEffect(() => {
    if (context) {
      setMessages([]);
      setChatId(null);
      setStreaming("");
      setInput("");
      setToolCalls([]);
      setThinkingStream("");
    }
  }, [context]);

  useEffect(() => {
    if (subscriptionRef.current) return;
    subscriptionRef.current = consumer.subscriptions.create(
      { channel: "AIChatChannel" },
      {
        received(data) {
          if (data.chat_id !== chatIdRef.current) return;
          if (data.type === "thinking") {
            setThinkingStream((prev) => prev + data.content);
          } else if (data.type === "thinking_done") {
            setThinkingDone(true);
            setThinkingDuration(data.duration);
          } else if (data.type === "tool_use") {
            setToolStatus(data.message);
            setToolLog((prev) => [...prev, { tool: data.tool, message: data.message }]);
            setToolCalls((prev) => [...prev, { id: data.tool_call_id, tool: data.tool, message: data.message, status: "running" }]);
          } else if (data.type === "tool_result") {
            setToolStatus("");
            setToolCalls((prev) => prev.map((tc) => tc.id === data.tool_call_id ? { ...tc, status: data.status, result: data.message } : tc));
          } else if (data.type === "chunk") {
            setToolStatus("");
            setStreaming((prev) => prev + data.content);
          } else if (data.type === "complete") {
            setMessages((prev) => [...prev, data.message]);
            setStreaming("");
            setSending(false);
            setToolStatus("");
            setToolLog([]);
            setToolCalls([]);
            setThinkingStream("");
            setThinkingDone(false);
            requestAnimationFrame(() => inputElRef.current?.focus());
            playNotificationSound();
          } else if (data.type === "error") {
            setMessages((prev) => [...prev, { role: "assistant", content: data.error }]);
            setStreaming("");
            setSending(false);
            setToolCalls([]);
            requestAnimationFrame(() => inputElRef.current?.focus());
          }
        },
      }
    );
    return () => {
      subscriptionRef.current?.unsubscribe();
      subscriptionRef.current = null;
    };
  }, []);

  async function sendMessage() {
    if (!input.trim() || sending) return;
    let content = input.trim();

    if (messages.length === 0 && (context || appContext)) {
      const parts = [];
      if (appContext) parts.push(appContext);
      if (context) parts.push(`Context:\n${context}`);
      content = parts.join("\n\n") + "\n\nUser question: " + content;
    }

    const userMessage = input.trim();
    setInput("");
    setReferences([]);
    setSending(true);
    setStreaming("");
    setThinkingStream("");
    setThinkingDone(false);
    setToolCalls([]);

    const token = document.querySelector('meta[name="csrf-token"]')?.content;
    let currentChatId = chatIdRef.current;

    if (!currentChatId) {
      const res = await fetch("/ai_chats", {
        method: "POST",
        headers: { "Content-Type": "application/json", "X-CSRF-Token": token },
        body: JSON.stringify({ context_url: window.location.pathname, model_id: selectedModel }),
      });
      const data = await res.json();
      currentChatId = data.id;
      setChatId(data.id);
    }

    setMessages((prev) => [...prev, { role: "user", content: userMessage }]);

    await fetch(`/ai_chats/${currentChatId}/message`, {
      method: "POST",
      headers: { "Content-Type": "application/json", "X-CSRF-Token": token },
      body: JSON.stringify({ content, references: [] }),
    });
  }

  function stopGenerating() {
    if (streaming) {
      setMessages((prev) => [...prev, { role: "assistant", content: streaming + " _(stopped)_" }]);
      setStreaming("");
    }
    setSending(false);
  }

  function newChat() {
    setChatId(null);
    setMessages([]);
    setStreaming("");
    setSending(false);
    setInput("");
    setToolCalls([]);
    setThinkingStream("");
  }

  async function executeAction(action, idx) {
    const key = `${idx}-${JSON.stringify(action)}`;
    if (executingActions[key] || executedActions[key]) return;
    setExecutingActions((prev) => ({ ...prev, [key]: true }));
    try {
      const token = document.querySelector('meta[name="csrf-token"]')?.content;
      const res = await fetch("/ai_chats/execute_action", {
        method: "POST",
        headers: { "Content-Type": "application/json", "X-CSRF-Token": token },
        body: JSON.stringify({ action_data: action }),
      });
      const data = await res.json();
      setExecutedActions((prev) => ({ ...prev, [key]: data }));
    } catch {
      setExecutedActions((prev) => ({ ...prev, [key]: { success: false, error: "Failed" } }));
    }
    setExecutingActions((prev) => ({ ...prev, [key]: false }));
  }

  return (
    <div className="flex flex-col h-full">
      {aiModels.length > 1 && (
        <div className="flex items-center gap-2 px-3 py-2 border-b shrink-0">
          <Select value={selectedModel} onValueChange={setSelectedModel} disabled={!!chatId}>
            <SelectTrigger className="h-7 text-sm flex-1">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {aiModels.map((model) => (
                <SelectItem key={model.value} value={model.value}>{model.label}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          {chatId && (
            <Button variant="ghost" size="xs" onClick={newChat}>
              + New
            </Button>
          )}
        </div>
      )}

      <AiChatMessages
        messages={messages}
        streaming={streaming}
        sending={sending}
        toolStatus={toolStatus}
        toolLog={toolLog}
        toolCalls={toolCalls}
        thinkingStream={thinkingStream}
        thinkingDone={thinkingDone}
        thinkingDuration={thinkingDuration}
        executingActions={executingActions}
        executedActions={executedActions}
        onExecuteAction={executeAction}
        onStop={stopGenerating}
        onSuggestion={(text) => { setInput(text); sendMessage(); }}
      />

      <AiChatInput
        input={input}
        onInputChange={setInput}
        references={references}
        onReferencesChange={setReferences}
        chatScope={chatScope}
        onChatScopeChange={setChatScope}
        sending={sending}
        chatId={chatId}
        onSend={sendMessage}
        onStop={stopGenerating}
      />
    </div>
  );
}

// frontend/pages/errors/EwAiChat.svelte
<script>
  import { usePage } from "@inertiajs/svelte";
  import { consumer } from "@/utils/cable";
  import { onDestroy } from "svelte";
  import AiChatMessages from "@/components/ai-chat/AiChatMessages.svelte";
  import AiChatInput from "@/components/ai-chat/AiChatInput.svelte";
  import { playNotificationSound } from "@/lib/notification-sounds.js";

  let { context = "", appContext = "" } = $props();

  const pageStore = usePage();
  let aiModels = $derived($pageStore.props.aiModels || []);
  let defaultAiModel = $derived($pageStore.props.defaultAiModel || "");
  let selectedModel = $state("");

  $effect(() => {
    if (selectedModel) return;
    if (defaultAiModel) selectedModel = defaultAiModel;
    else if (aiModels.length > 0) selectedModel = aiModels[0].value;
  });

  // Chat state
  let chatId = $state(null);
  let messages = $state([]);
  let input = $state("");
  let references = $state([]);
  let sending = $state(false);
  let streaming = $state("");
  let toolStatus = $state("");
  let toolLog = $state([]);
  let toolCalls = $state([]);
  let thinkingStream = $state("");
  let thinkingDone = $state(false);
  let thinkingDuration = $state(0);
  let executingActions = $state({});
  let executedActions = $state({});
  let chatScope = $state("standard");
  let messagesEl = $state(null);
  let inputComp;

  // WebSocket
  let subscription = null;

  function subscribe() {
    if (subscription) return;
    subscription = consumer.subscriptions.create(
      { channel: "AIChatChannel" },
      {
        received(data) {
          if (data.chat_id !== chatId) return;
          if (data.type === "thinking") {
            thinkingStream += data.content;
          } else if (data.type === "thinking_done") {
            thinkingDone = true;
            thinkingDuration = data.duration;
          } else if (data.type === "tool_use") {
            toolStatus = data.message;
            toolLog = [...toolLog, { tool: data.tool, message: data.message }];
            toolCalls = [...toolCalls, { id: data.tool_call_id, tool: data.tool, message: data.message, status: "running" }];
          } else if (data.type === "tool_result") {
            toolStatus = "";
            toolCalls = toolCalls.map(tc => tc.id === data.tool_call_id ? { ...tc, status: data.status, result: data.message } : tc);
          } else if (data.type === "chunk") {
            toolStatus = "";
            streaming += data.content;
          } else if (data.type === "complete") {
            messages = [...messages, data.message];
            streaming = "";
            sending = false;
            toolStatus = "";
            toolLog = [];
            toolCalls = [];
            thinkingStream = "";
            thinkingDone = false;
            requestAnimationFrame(() => inputComp?.focus?.());
            playNotificationSound();
          } else if (data.type === "error") {
            messages = [...messages, { role: "assistant", content: data.error }];
            streaming = "";
            sending = false;
            toolCalls = [];
            requestAnimationFrame(() => inputComp?.focus?.());
          }
        }
      }
    );
  }

  $effect(() => {
    subscribe();
    return () => { subscription?.unsubscribe(); subscription = null; };
  });

  // Reset when context changes
  $effect(() => {
    if (context) {
      messages = [];
      chatId = null;
      streaming = "";
      input = "";
      toolCalls = [];
      thinkingStream = "";
    }
  });

  export function focus() {
    setTimeout(() => inputComp?.focusInput?.() || document.querySelector(".ai-chat-input textarea")?.focus(), 50);
  }

  async function sendMessage() {
    if (!input.trim() || sending) return;
    let content = input.trim();

    // Prepend context on first message
    if (messages.length === 0 && (context || appContext)) {
      const parts = [];
      if (appContext) parts.push(appContext);
      if (context) parts.push(`Context:\n${context}`);
      content = parts.join("\n\n") + "\n\nUser question: " + content;
    }

    const userMessage = input.trim();
    input = "";
    references = [];
    sending = true;
    streaming = "";
    thinkingStream = "";
    thinkingDone = false;
    toolCalls = [];

    const token = document.querySelector('meta[name="csrf-token"]')?.content;

    if (!chatId) {
      const res = await fetch("/ai_chats", {
        method: "POST",
        headers: { "Content-Type": "application/json", "X-CSRF-Token": token },
        body: JSON.stringify({ context_url: window.location.pathname, model_id: selectedModel }),
      });
      const data = await res.json();
      chatId = data.id;
    }

    messages = [...messages, { role: "user", content: userMessage }];

    await fetch(`/ai_chats/${chatId}/message`, {
      method: "POST",
      headers: { "Content-Type": "application/json", "X-CSRF-Token": token },
      body: JSON.stringify({ content, references: [] }),
    });
  }

  function stopGenerating() {
    if (streaming) {
      messages = [...messages, { role: "assistant", content: streaming + " _(stopped)_" }];
      streaming = "";
    }
    sending = false;
  }

  function newChat() {
    chatId = null;
    messages = [];
    streaming = "";
    sending = false;
    input = "";
    toolCalls = [];
    thinkingStream = "";
  }

  async function executeAction(action, idx) {
    const key = `${idx}-${JSON.stringify(action)}`;
    if (executingActions[key] || executedActions[key]) return;
    executingActions = { ...executingActions, [key]: true };
    try {
      const token = document.querySelector('meta[name="csrf-token"]')?.content;
      const res = await fetch("/ai_chats/execute_action", {
        method: "POST",
        headers: { "Content-Type": "application/json", "X-CSRF-Token": token },
        body: JSON.stringify({ action_data: action }),
      });
      const data = await res.json();
      executedActions = { ...executedActions, [key]: data };
    } catch {
      executedActions = { ...executedActions, [key]: { success: false, error: "Failed" } };
    }
    executingActions = { ...executingActions, [key]: false };
  }

  onDestroy(() => {
    subscription?.unsubscribe();
  });
</script>

<div class="ew-ai-chat">
  {#if aiModels.length > 1}
    <div class="ew-ai-model-row">
      <select class="ew-ai-model-select" bind:value={selectedModel} disabled={!!chatId}>
        {#each aiModels as model}
          <option value={model.value}>{model.label}</option>
        {/each}
      </select>
      {#if chatId}
        <button class="ew-ai-new" onclick={newChat} title="New chat">+ New</button>
      {/if}
    </div>
  {/if}

  <AiChatMessages
    {messages}
    {streaming}
    {sending}
    {toolStatus}
    {toolLog}
    {toolCalls}
    {thinkingStream}
    {thinkingDone}
    {thinkingDuration}
    {executingActions}
    {executedActions}
    onExecuteAction={executeAction}
    onStop={stopGenerating}
    onSuggestion={(text) => { input = text; sendMessage(); }}
    onMessagesElReady={el => messagesEl = el}
  />

  <AiChatInput
    bind:input
    bind:references
    bind:chatScope
    {sending}
    {chatId}
    onSend={sendMessage}
    onStop={stopGenerating}
    bind:this={inputComp}
  />
</div>

<style>
  .ew-ai-chat {
    display: flex;
    flex-direction: column;
    height: 100%;
    min-height: 300px;
    padding: 0.75rem 1rem 1rem;
  }

  .ew-ai-model-row {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding-bottom: 0.5rem;
    border-bottom: 1px solid var(--color-border);
    margin-bottom: 0.5rem;
  }

  .ew-ai-model-select {
    padding: 0.1875rem 1.25rem 0.1875rem 0.375rem;
    font-size: 0.6875rem;
    font-weight: 500;
    font-family: inherit;
    border: 1px solid var(--color-border);
    border-radius: var(--radius-sm, 0.375rem);
    background: var(--color-bg);
    color: var(--color-fg);
    box-shadow: var(--shadow-xs, 0 1px 2px rgba(0, 0, 0, 0.03));
    outline: none;
    cursor: pointer;
    appearance: none;
    background-image: url("data:image/svg+xml,%3Csvg width='8' height='5' viewBox='0 0 8 5' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M1 1l3 3 3-3' stroke='%239ca3af' stroke-width='1.5' stroke-linecap='round' stroke-linejoin='round'/%3E%3C/svg%3E");
    background-repeat: no-repeat;
    background-position: right 0.375rem center;

    &:focus { border-color: var(--color-focus); box-shadow: 0 0 0 2px var(--color-focus-ring); }
    &:disabled { opacity: 0.6; cursor: not-allowed; }
  }

  .ew-ai-new {
    font-size: 0.6875rem;
    font-weight: 500;
    font-family: inherit;
    padding: 0.25rem 0.5rem;
    border: 1px solid var(--color-border);
    border-radius: var(--radius-sm, 0.375rem);
    background: var(--color-bg);
    color: var(--color-muted);
    cursor: pointer;
    margin-left: auto;
    transition: all 0.1s;

    &:hover { background: var(--color-accent); color: var(--color-fg); }
  }
</style>
