// frontend/pages/mail_events/index.jsx
import { useState } from "react";
import { router, InfiniteScroll } from "@inertiajs/react";
import DaylightLayout from "../DaylightLayout";
import PeriodSelect from "../PeriodSelect";
import EwSheet from "../errors/EwSheet";
import InteractiveBarChart from "@/components/charts/InteractiveBarChart";
import { ExportButton } from "@/components/ui/export-button";
import { SortableHeader } from "@/components/ui/sortable-header";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { fmt, timeAgo, formatTime } from "@/lib/formatters.js";

export default function MailEventsIndex({
  mailers = [], events = [], totals = {}, period = "24h", selected_mailer = null,
  volume_series = [], base_path: base = "/daylight",
  sort_column = null, sort_direction = null,
}) {
  const [sheetOpen, setSheetOpen] = useState(false);
  const [sheetItem, setSheetItem] = useState(null);
  const [sheetType, setSheetType] = useState("mailer");

  const deliveryRate = totals.total > 0
    ? Math.round(((totals.delivered || 0) / totals.total) * 100)
    : 0;

  const deliveryRateColor = deliveryRate >= 95 ? "#22c55e" : deliveryRate >= 80 ? "#f59e0b" : "#ef4444";

  const sheetTitle = sheetType === "mailer"
    ? (sheetItem?.mailer_class || "Mailer")
    : `${sheetItem?.mailer_class || "Mail"}: ${sheetItem?.subject || "Event"}`;

  const sheetAi = (() => {
    if (!sheetItem) return "";
    if (sheetType === "mailer") return `Mailer Class: ${sheetItem.mailer_class}\nTotal: ${sheetItem.total}\nDelivered: ${sheetItem.delivered_count}\nFailed: ${sheetItem.failed_count}\nAvg duration: ${fmt(sheetItem.avg_duration)}`;
    return `Mailer: ${sheetItem.mailer_class}\nSubject: ${sheetItem.subject || "—"}\nRecipients: ${sheetItem.recipients || "—"}\nChannel: ${sheetItem.channel || "email"}\nStatus: ${sheetItem.status || "—"}\nTime: ${sheetItem.occurred_at}`;
  })();

  function changePeriod(p) { router.get(`${base}/mail_events`, { period: p }, { preserveState: true }); }
  function openMailer(ml) { setSheetItem(ml); setSheetType("mailer"); setSheetOpen(true); }
  function openEvent(ev) { setSheetItem(ev); setSheetType("event"); setSheetOpen(true); }

  const chartData = volume_series.map((d) => ({ t: d.t, mail: d.v }));

  function statusVariant(status) {
    if (status === "delivered") return "default";
    if (status === "failed") return "destructive";
    return "secondary";
  }

  return (
    <DaylightLayout>
      <div className="dl-page">
        <div className="dl-page-header">
          <div>
            <h1 className="dl-page-title">Mail &amp; Notifications</h1>
            <p className="dl-page-subtitle">Email and notification delivery monitoring</p>
          </div>
          <div className="header-controls">
            <ExportButton baseUrl={`${base}/mail_events/export`} />
            <PeriodSelect value={period} onChange={changePeriod} />
          </div>
        </div>

        <div className="dl-stat-grid">
          <div className="stat-card"><span className="stat-card-label">Total Sent</span><span className="stat-card-value">{totals.total || 0}</span></div>
          <div className="stat-card"><span className="stat-card-label">Delivered</span><span className="stat-card-value" style={{ color: "#22c55e" }}>{totals.delivered || 0}</span></div>
          <div className={`stat-card${totals.failed > 0 ? " stat-card-danger" : ""}`}>
            <span className="stat-card-label">Failed</span>
            <span className="stat-card-value">{totals.failed || 0}</span>
          </div>
          <div className="stat-card">
            <span className="stat-card-label">Delivery Rate</span>
            <span className="stat-card-value" style={{ color: deliveryRateColor }}>{deliveryRate}%</span>
          </div>
        </div>

        {volume_series.length > 0 && (
          <InteractiveBarChart
            data={chartData}
            series={[{ key: "mail", label: "Mail Sent", color: "#8b5cf6" }]}
            title="Mail Volume"
            description="Mail delivery over time"
            height={250}
          />
        )}

        {mailers.length > 0 && (
          <div className="section">
            <h2 className="section-title">Mailer Classes</h2>
            <div className="dl-data-table">
              <InfiniteScroll data="mailers" itemsElement="#mailers-tbody" startElement="#mailers-thead">
                <table className="dl-table">
                  <thead id="mailers-thead">
                    <tr>
                      <th style={{ flex: 2 }}>Mailer Class</th>
                      <th style={{ width: "4rem", textAlign: "right" }}><SortableHeader column="total" label="Total" sort_column={sort_column} sort_direction={sort_direction} /></th>
                      <th style={{ width: "5rem", textAlign: "right" }}><SortableHeader column="delivered_count" label="Delivered" sort_column={sort_column} sort_direction={sort_direction} /></th>
                      <th style={{ width: "4rem", textAlign: "right" }}><SortableHeader column="failed_count" label="Failed" sort_column={sort_column} sort_direction={sort_direction} /></th>
                      <th style={{ width: "5rem", textAlign: "right" }}><SortableHeader column="avg_duration" label="Avg" sort_column={sort_column} sort_direction={sort_direction} /></th>
                    </tr>
                  </thead>
                  <tbody id="mailers-tbody">
                    {mailers.map((ml, i) => (
                      <tr key={`${ml.mailer_class}:${i}`} className="row" onClick={() => openMailer(ml)} style={{ cursor: "pointer" }}>
                        <td className="cell" style={{ flex: 2 }}><span className="mailer-name">{ml.mailer_class}</span></td>
                        <td className="cell num" style={{ width: "4rem" }}>{ml.total}</td>
                        <td className="cell num delivered" style={{ width: "5rem" }}>{ml.delivered_count}</td>
                        <td className={`cell num${ml.failed_count > 0 ? " failed-val" : ""}`} style={{ width: "4rem" }}>{ml.failed_count}</td>
                        <td className="cell num" style={{ width: "5rem" }}>{fmt(ml.avg_duration)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </InfiniteScroll>
            </div>
          </div>
        )}

        {events.length > 0 ? (
          <div className="section">
            <h2 className="section-title">Recent Events</h2>
            <div className="dl-data-table">
              <div className="dl-table-header">
                <div className="dl-th" style={{ flex: 1.5 }}>Mailer</div>
                <div className="dl-th" style={{ flex: 1 }}>Subject</div>
                <div className="dl-th" style={{ width: "5rem" }}>Status</div>
                <div className="dl-th" style={{ width: "4rem" }}>Channel</div>
                <div className="dl-th dl-th-right" style={{ width: "5.5rem" }}>When</div>
              </div>
              {events.map((ev) => (
                <Button key={ev.id} variant="ghost" className="dl-table-row w-full justify-start h-auto rounded-none" onClick={() => openEvent(ev)}>
                  <div className="dl-td" style={{ flex: 1.5 }}><span className="event-mailer">{ev.mailer_class || "Unknown"}</span></div>
                  <div className="dl-td" style={{ flex: 1 }}><span className="event-subject">{ev.subject || "—"}</span></div>
                  <div className="dl-td" style={{ width: "5rem" }}>
                    <Badge variant={statusVariant(ev.status)}>
                      {ev.status || "—"}
                    </Badge>
                  </div>
                  <div className="dl-td" style={{ width: "4rem" }}><span className="event-channel">{ev.channel || "email"}</span></div>
                  <div className="dl-td dl-td-num" style={{ width: "5.5rem" }}><span className="event-time">{timeAgo(ev.occurred_at)}</span></div>
                </Button>
              ))}
            </div>
          </div>
        ) : mailers.length === 0 ? (
          <div className="empty-state">
            <div className="empty-icon">
              <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="#cbd5e1" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22,6 12,13 2,6"/>
              </svg>
            </div>
            <p className="empty-title">No mail data yet</p>
            <p className="empty-sub">Mail events will appear here once your app starts sending emails.</p>
          </div>
        ) : null}
      </div>

      <EwSheet open={sheetOpen} onClose={() => setSheetOpen(false)} title={sheetTitle} aiContext={sheetAi}>
        {sheetItem && (
          <div className="dl-sheet-detail">
            {sheetType === "mailer" ? (
              <dl className="dl-dl">
                <div className="dl-dl-row"><dt>Mailer Class</dt><dd>{sheetItem.mailer_class}</dd></div>
                <div className="dl-dl-row"><dt>Total</dt><dd>{sheetItem.total}</dd></div>
                <div className="dl-dl-row"><dt>Delivered</dt><dd className="ok">{sheetItem.delivered_count}</dd></div>
                <div className="dl-dl-row"><dt>Failed</dt><dd className={sheetItem.failed_count > 0 ? "err" : ""}>{sheetItem.failed_count}</dd></div>
                <div className="dl-dl-row"><dt>Avg Duration</dt><dd>{fmt(sheetItem.avg_duration)}</dd></div>
              </dl>
            ) : (
              <>
                <dl className="dl-dl">
                  <div className="dl-dl-row"><dt>Mailer Class</dt><dd>{sheetItem.mailer_class}</dd></div>
                  <div className="dl-dl-row"><dt>Subject</dt><dd>{sheetItem.subject || "—"}</dd></div>
                  <div className="dl-dl-row"><dt>Recipients</dt><dd>{sheetItem.recipients || "—"}</dd></div>
                  <div className="dl-dl-row"><dt>Channel</dt><dd><Badge variant="secondary">{sheetItem.channel || "email"}</Badge></dd></div>
                  <div className="dl-dl-row">
                    <dt>Status</dt>
                    <dd>
                      <Badge variant={statusVariant(sheetItem.status)}>
                        {sheetItem.status || "—"}
                      </Badge>
                    </dd>
                  </div>
                  {sheetItem.duration_ms && <div className="dl-dl-row"><dt>Duration</dt><dd>{fmt(sheetItem.duration_ms)}</dd></div>}
                  <div className="dl-dl-row"><dt>Time</dt><dd>{formatTime(sheetItem.occurred_at)}</dd></div>
                </dl>
                {sheetItem.error_message && (
                  <>
                    <h4 className="sheet-sub">Error</h4>
                    <pre className="sheet-pre">{sheetItem.error_message}</pre>
                  </>
                )}
              </>
            )}
          </div>
        )}
      </EwSheet>
    </DaylightLayout>
  );
}

// frontend/pages/mail_events/index.svelte
<script>
  import { router } from "@inertiajs/svelte";
  import DaylightLayout from "../DaylightLayout.svelte";
  import Badge from "@/components/ui/Badge.svelte";
  import Button from "@/components/ui/Button.svelte";
  import Table from "@/components/ui/Table.svelte";
  import SortableHeader from "@/components/ui/SortableHeader.svelte";
  import PeriodSelect from "../PeriodSelect.svelte";
  import EwSheet from "../errors/EwSheet.svelte";
  import TimeSeriesChart from "@/components/charts/TimeSeriesChart.svelte";
  import ExportButton from "@/components/ui/ExportButton.svelte";
  import InfiniteScroll from "@/components/ui/InfiniteScroll.svelte";
  import { fmt, timeAgo, formatTime } from "@/lib/formatters.js";

  let { mailers = [], events = [], totals = {}, period = "24h", volume_series = [], page = 1, has_more = false, base_path: base = "/daylight", sort_column = null, sort_direction = null } = $props();

  let sheetOpen = $state(false);
  let sheetItem = $state(null);
  let sheetType = $state("mailer");

  function changePeriod(p) { router.get(`${base}/mail_events`, { period: p }, { preserveState: true }); }

  function openMailer(ml) { sheetItem = ml; sheetType = "mailer"; sheetOpen = true; }
  function openEvent(ev) { sheetItem = ev; sheetType = "event"; sheetOpen = true; }

  let sheetTitle = $derived(
    sheetType === "mailer" ? (sheetItem?.mailer_class || "Mailer") :
    `${sheetItem?.mailer_class || "Mail"}: ${sheetItem?.subject || "Event"}`
  );

  let sheetAi = $derived.by(() => {
    if (!sheetItem) return "";
    if (sheetType === "mailer") return `Mailer Class: ${sheetItem.mailer_class}\nTotal: ${sheetItem.total}\nDelivered: ${sheetItem.delivered_count}\nFailed: ${sheetItem.failed_count}\nAvg duration: ${fmt(sheetItem.avg_duration)}`;
    return `Mailer: ${sheetItem.mailer_class}\nSubject: ${sheetItem.subject || "—"}\nRecipients: ${sheetItem.recipients || "—"}\nChannel: ${sheetItem.channel || "email"}\nStatus: ${sheetItem.status || "—"}\nTime: ${sheetItem.occurred_at}`;
  });

  let deliveryRate = $derived(totals.total > 0 ? Math.round(((totals.delivered || 0) / totals.total) * 100) : 0);

  let allMailers = $state(mailers);
  let currentPage = $state(page);
  let loadingMore = $state(false);

  $effect(() => {
    period;
    allMailers = mailers;
    currentPage = page;
  });

  function loadMore() {
    if (loadingMore || !has_more) return;
    loadingMore = true;
    router.get(`${base}/mail_events`, { period, page: currentPage + 1 }, {
      preserveState: true,
      preserveScroll: true,
      only: ['mailers', 'page', 'has_more'],
      onSuccess: (p) => {
        const newItems = p.props.mailers || [];
        allMailers = [...allMailers, ...newItems];
        currentPage = p.props.page;
        has_more = p.props.has_more;
        loadingMore = false;
      },
      onError: () => { loadingMore = false; }
    });
  }
</script>

<svelte:head><title>Mail & Notifications — Daylight</title></svelte:head>

<DaylightLayout>
  <div class="dl-page">
    <!-- Header -->
    <div class="dl-page-header">
      <div>
        <h1 class="dl-page-title">Mail & Notifications</h1>
        <p class="dl-page-subtitle">Email and notification delivery monitoring</p>
      </div>
      <div class="header-controls">
        <ExportButton baseUrl={`${base}/mail_events/export`} />
        <PeriodSelect value={period} onchange={changePeriod} />
      </div>
    </div>

    <!-- Stat Cards -->
    <div class="dl-stat-grid">
      <div class="stat-card">
        <span class="stat-card-label">Total Sent</span>
        <span class="stat-card-value">{totals.total || 0}</span>
      </div>
      <div class="stat-card">
        <span class="stat-card-label">Delivered</span>
        <span class="stat-card-value" style="color: #22c55e">{totals.delivered || 0}</span>
      </div>
      <div class="stat-card {totals.failed > 0 ? 'stat-card-danger' : ''}">
        <span class="stat-card-label">Failed</span>
        <span class="stat-card-value">{totals.failed || 0}</span>
      </div>
      <div class="stat-card">
        <span class="stat-card-label">Delivery Rate</span>
        <span class="stat-card-value" style="color: {deliveryRate >= 95 ? '#22c55e' : deliveryRate >= 80 ? '#f59e0b' : '#ef4444'}">{deliveryRate}%</span>
      </div>
    </div>

    <!-- Volume Time Series -->
    {#if volume_series.length > 0}
      <div class="chart-section">
        <TimeSeriesChart
          data={volume_series}
          width={720}
          height={180}
          color="#8b5cf6"
          label="Mail volume over time"
          showArea={true}
        />
      </div>
    {/if}

    <!-- Mailers Table -->
    {#if allMailers.length > 0}
      <div class="section">
        <h2 class="section-title">Mailer Classes</h2>
        <div class="dl-data-table">
          <div class="dl-table-header">
            <div class="dl-th" style="flex:2">Mailer Class</div>
            <div class="dl-th dl-th-right" style="width:4rem"><SortableHeader column="total" label="Total" {sort_column} {sort_direction} /></div>
            <div class="dl-th dl-th-right" style="width:5rem"><SortableHeader column="delivered_count" label="Delivered" {sort_column} {sort_direction} /></div>
            <div class="dl-th dl-th-right" style="width:4rem"><SortableHeader column="failed_count" label="Failed" {sort_column} {sort_direction} /></div>
            <div class="dl-th dl-th-right" style="width:5rem"><SortableHeader column="avg_duration" label="Avg" {sort_column} {sort_direction} /></div>
          </div>
          {#each allMailers as ml, i (ml.mailer_class + ':' + i)}
            <button class="dl-table-row" onclick={() => openMailer(ml)}>
              <div class="dl-td" style="flex:2"><span class="mailer-name">{ml.mailer_class}</span></div>
              <div class="dl-td dl-td-num" style="width:4rem">{ml.total}</div>
              <div class="dl-td dl-td-num delivered" style="width:5rem">{ml.delivered_count}</div>
              <div class="dl-td dl-td-num" style="width:4rem" class:failed-val={ml.failed_count > 0}>{ml.failed_count}</div>
              <div class="dl-td dl-td-num" style="width:5rem">{fmt(ml.avg_duration)}</div>
            </button>
          {/each}
          <InfiniteScroll loading={loadingMore} hasMore={has_more} onLoadMore={loadMore} />
        </div>
      </div>
    {/if}

    <!-- Recent Events -->
    {#if events.length > 0}
      <div class="section">
        <h2 class="section-title">Recent Events</h2>
        <div class="dl-data-table">
          <div class="dl-table-header">
            <div class="dl-th" style="flex:1.5">Mailer</div>
            <div class="dl-th" style="flex:1">Subject</div>
            <div class="dl-th" style="width:5rem">Status</div>
            <div class="dl-th" style="width:4rem">Channel</div>
            <div class="dl-th dl-th-right" style="width:5.5rem">When</div>
          </div>
          {#each events as ev (ev.id)}
            <button class="dl-table-row" onclick={() => openEvent(ev)}>
              <div class="dl-td" style="flex:1.5">
                <span class="event-mailer">{ev.mailer_class || "Unknown"}</span>
              </div>
              <div class="dl-td" style="flex:1">
                <span class="event-subject">{ev.subject || "—"}</span>
              </div>
              <div class="dl-td" style="width:5rem">
                <span class="event-status" class:status-delivered={ev.status === "delivered"} class:status-failed={ev.status === "failed"}>{ev.status || "—"}</span>
              </div>
              <div class="dl-td" style="width:4rem">
                <span class="event-channel">{ev.channel || "email"}</span>
              </div>
              <div class="dl-td dl-td-num" style="width:5.5rem">
                <span class="event-time">{timeAgo(ev.occurred_at)}</span>
              </div>
            </button>
          {/each}
        </div>
      </div>
    {:else if allMailers.length === 0}
      <div class="empty-state">
        <div class="empty-icon">
          <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="#cbd5e1" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
            <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22,6 12,13 2,6"/>
          </svg>
        </div>
        <p class="empty-title">No mail data yet</p>
        <p class="empty-sub">Mail events will appear here once your app starts sending emails.</p>
      </div>
    {/if}
  </div>
</DaylightLayout>

<EwSheet bind:open={sheetOpen} title={sheetTitle} aiContext={sheetAi}>
  {#if sheetItem}
    <div class="dl-sheet-detail">
      {#if sheetType === "mailer"}
        <dl class="dl-dl">
          <div class="dl-dl-row"><dt>Mailer Class</dt><dd>{sheetItem.mailer_class}</dd></div>
          <div class="dl-dl-row"><dt>Total</dt><dd>{sheetItem.total}</dd></div>
          <div class="dl-dl-row"><dt>Delivered</dt><dd class="ok">{sheetItem.delivered_count}</dd></div>
          <div class="dl-dl-row"><dt>Failed</dt><dd class:err={sheetItem.failed_count > 0}>{sheetItem.failed_count}</dd></div>
          <div class="dl-dl-row"><dt>Avg Duration</dt><dd>{fmt(sheetItem.avg_duration)}</dd></div>
        </dl>

      {:else}
        <dl class="dl-dl">
          <div class="dl-dl-row"><dt>Mailer Class</dt><dd>{sheetItem.mailer_class}</dd></div>
          <div class="dl-dl-row"><dt>Subject</dt><dd>{sheetItem.subject || "—"}</dd></div>
          <div class="dl-dl-row"><dt>Recipients</dt><dd>{sheetItem.recipients || "—"}</dd></div>
          <div class="dl-dl-row"><dt>Channel</dt><dd><span class="channel-badge">{sheetItem.channel || "email"}</span></dd></div>
          <div class="dl-dl-row"><dt>Status</dt><dd><span class="event-status" class:status-delivered={sheetItem.status === "delivered"} class:status-failed={sheetItem.status === "failed"}>{sheetItem.status || "—"}</span></dd></div>
          {#if sheetItem.duration_ms}<div class="dl-dl-row"><dt>Duration</dt><dd>{fmt(sheetItem.duration_ms)}</dd></div>{/if}
          <div class="dl-dl-row"><dt>Time</dt><dd>{formatTime(sheetItem.occurred_at)}</dd></div>
        </dl>
        {#if sheetItem.error_message}
          <h4 class="sheet-sub">Error</h4>
          <pre class="sheet-pre">{sheetItem.error_message}</pre>
        {/if}
      {/if}
    </div>
  {/if}
</EwSheet>

<style>
  .header-controls { display: flex; align-items: center; gap: 0.5rem; }
  .section { display: flex; flex-direction: column; gap: 0.75rem; }
  .section-title { font-size: 0.875rem; font-weight: 600; color: var(--color-fg); margin: 0; }

  .chart-section {
    background: var(--color-bg);
    border: 1px solid var(--color-border);
    border-radius: 0.75rem;
    padding: 1.25rem;
  }

  /* Stat Cards */
  .stat-card {
    background: var(--color-bg);
    border: 1px solid var(--color-border);
    border-radius: 0.75rem;
    padding: 1.25rem;
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
  }
  .stat-card-label { font-size: 0.8125rem; font-weight: 500; color: var(--color-muted); }
  .stat-card-value { font-size: 1.75rem; font-weight: 700; color: var(--color-fg); letter-spacing: -0.02em; line-height: 1; font-variant-numeric: tabular-nums; }
  .stat-card-danger { border-color: var(--color-danger-border); background: var(--color-danger-bg); }
  .stat-card-danger .stat-card-value { color: var(--color-danger); }

  /* Table cell variants */
  .delivered { color: var(--color-success); }
  .failed-val { color: var(--color-danger); font-weight: 600; }
  .mailer-name { font-size: 0.8125rem; font-weight: 600; color: var(--color-fg); }
  .event-mailer { font-size: 0.8125rem; font-weight: 600; color: var(--color-fg); }
  .event-subject { font-size: 0.75rem; color: var(--color-fg-tertiary); }
  .event-time { font-size: 0.75rem; color: var(--color-muted-light); font-variant-numeric: tabular-nums; }

  /* Status badges */
  .event-status {
    font-size: 0.6875rem; font-weight: 600; text-transform: capitalize;
    padding: 0.125rem 0.5rem; border-radius: 9999px;
    background: var(--color-accent); color: var(--color-muted);
  }
  .status-delivered { background: var(--color-status-2xx-bg); color: var(--color-status-2xx); }
  .status-failed { background: var(--color-status-5xx-bg); color: var(--color-danger-hover); }

  .event-channel {
    font-size: 0.6875rem; color: var(--color-muted);
    background: var(--color-accent); padding: 0.125rem 0.5rem; border-radius: 0.25rem;
  }
  .channel-badge {
    font-size: 0.6875rem; color: var(--color-muted);
    padding: 0.125rem 0.5rem; background: var(--color-accent); border-radius: 0.25rem;
  }

  /* Sheet extras */
  .ok { color: var(--color-success); }
  .err { color: var(--color-danger); font-weight: 600; }
  .sheet-sub { font-size: 0.6875rem; font-weight: 600; color: var(--color-muted-light); text-transform: uppercase; letter-spacing: 0.04em; margin: 0; }
  .sheet-pre { font-size: 0.6875rem; font-family: "SF Mono", Monaco, Menlo, monospace; background: var(--color-danger-subtle); padding: 0.75rem; border: 1px solid var(--color-danger-border); border-radius: 0.5rem; overflow-x: auto; white-space: pre-wrap; word-break: break-all; margin: 0; color: var(--color-danger); line-height: 1.6; }

  /* Empty state */
  .empty-state {
    display: flex; flex-direction: column; align-items: center; justify-content: center;
    padding: 3rem 1rem; background: var(--color-bg);
    border: 1px solid var(--color-border); border-radius: 0.75rem; text-align: center;
  }
  .empty-icon { margin-bottom: 1rem; }
  .empty-title { font-size: 0.9375rem; font-weight: 600; color: var(--color-fg); margin: 0; }
  .empty-sub { font-size: 0.8125rem; color: var(--color-muted-light); margin: 0.25rem 0 0; }
</style>
