// frontend/components/settings/PerformanceIssues.jsx
import { useState } from "react";
import { router } from "@inertiajs/react";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import IssueCard from "@/components/settings/IssueCard.jsx";

const typeLabels = {
  n_plus_one: "N+1 Query",
  slow_query: "Slow Query",
  counter_cache: "Counter Cache",
};

export default function PerformanceIssues({ issues = [], base = "/daylight" }) {
  const [expandedIssue, setExpandedIssue] = useState(null);

  function toggleIssue(id) {
    setExpandedIssue(expandedIssue === id ? null : id);
  }

  function dismissIssue(id, status) {
    router.patch(`${base}/settings/performance_issues/${id}`, { new_status: status }, { preserveScroll: true });
  }

  if (issues.length === 0) return null;

  return (
    <Card>
      <CardHeader className="border-b py-4">
        <div className="flex items-center gap-2">
          <CardTitle className="text-sm">Performance Issues</CardTitle>
          <Badge variant="outline">{issues.length} open</Badge>
        </div>
      </CardHeader>
      <CardContent className="p-4 flex flex-col gap-2">
        {issues.map((issue) => (
          <IssueCard
            key={issue.id}
            issue={issue}
            expanded={expandedIssue === issue.id}
            onToggle={toggleIssue}
            onDismiss={dismissIssue}
            variant="performance"
            typeLabel={typeLabels[issue.issue_type] || issue.issue_type}
            typeClass={issue.issue_type}
          />
        ))}
      </CardContent>
    </Card>
  );
}

// frontend/pages/settings/PerformanceIssues.svelte
<script>
  import { router } from "@inertiajs/svelte";
  import IssueCard from "./IssueCard.svelte";

  let { issues = [], base = "/daylight" } = $props();
  let expandedIssue = $state(null);

  function toggleIssue(id) { expandedIssue = expandedIssue === id ? null : id; }

  function dismissIssue(id, status) {
    router.patch(`${base}/settings/performance_issues/${id}`, { new_status: status }, { preserveScroll: true });
  }

  const typeLabels = {
    n_plus_one: "N+1 Query",
    slow_query: "Slow Query",
    counter_cache: "Counter Cache"
  };
</script>

{#if issues.length > 0}
  <div class="issues-section">
    <div class="issues-header">
      <h2 class="section-title">Performance Issues</h2>
      <span class="issues-count">{issues.length} open</span>
    </div>

    <div class="issues-list">
      {#each issues as issue (issue.id)}
        <IssueCard
          {issue}
          expanded={expandedIssue === issue.id}
          ontoggle={toggleIssue}
          ondismiss={dismissIssue}
          variant="performance"
          typeLabel={typeLabels[issue.issue_type] || issue.issue_type}
          typeClass={issue.issue_type}
        />
      {/each}
    </div>
  </div>
{/if}

<style>
  .issues-section {
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  .issues-header {
    display: flex;
    align-items: center;
    gap: 0.75rem;
  }

  .section-title {
    font-size: 0.9375rem;
    font-weight: 600;
    color: var(--color-fg);
    margin: 0;
  }

  .issues-count {
    font-size: 0.75rem;
    font-weight: 600;
    padding: 0.125rem 0.5rem;
    border-radius: 9999px;
    background: var(--color-warning-subtle);
    color: var(--color-warning-dark);
    border: 1px solid var(--color-warning-border);
  }

  .issues-list {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }

  /* Performance-specific type badge colors */
  :global(.issue-type-badge.n_plus_one) {
    background: var(--color-danger-subtle);
    color: var(--color-danger);
  }

  :global(.issue-type-badge.slow_query) {
    background: var(--color-warning-subtle);
    color: var(--color-warning-dark);
  }

  :global(.issue-type-badge.counter_cache) {
    background: var(--color-info-subtle);
    color: var(--color-info);
  }
</style>
